### ISSUE TITLE
Certain Google Meet times cause an exception

### ISSUE THREAD

**Issue by BernardoGomesNegri** [BernardoGomesNegri/WhatsappGroupAnalysis#1]
Uma exceção ocorrerá se um log do arquivo do Google Meet tiver tempo menor que 10 segundos. Por exemplo: 32:10:6 causará uma exceção já que o método DateTime.ParseExact do .NET não aceitará o "6", só "06". Como o Google Meet escreve desse jeito, é um problema relativamente grande.

### Como reproduzir:

Faça um arquivo de texto com o texto seguinte: 

    {"mimetype":"text/plain","data":"10:10:6.524,10:10:9.524\nPessoa Pessoa Pessoa: texto"}

Rode o programa com esse arquivo. Tenha certeza de usar o parâmetro "platform:googlemeet"

**Comment by negri** [comment]
Creio que a solução é, na Regex de detecção. colocar \d{1,2} na parte do
segundo.

E no ParseExact colocar s ao invés de ss, mas será preciso cortar a string
original, procurando o primeiro ponto.

**Comment by BernardoGomesNegri** [comment]
Issue closed with commit number 718d691050a14fcf2fe633ba02915430be05083f
